import GovTech from "../public/govtech.png";
import Coupang from "../public/coupang.png";
import DXC from "../public/dxc.png";
import Singtel from "../public/singtel.png";
import TikTok from "../public/tiktok.png";
import Jala from "../public/jala.png";

export const jobListings = [
  {
    company: "GovTech",
    job_title: "Technical Product Manager (Cloud)",
    age: "less than a minute",
    location: "Singapore",
    rating: "4",
    starting_pay: "6,722",
    ending_pay: "11,278",
    role: "PM",
    stack: ["Rest API", "Docker", "Oracle", "Container"],
    img: GovTech,
  },
  {
    company: "DXC Technology",
    job_title: "Tech Lead",
    age: "2 days",
    location: "Singapore",
    rating: "3.2",
    starting_pay: "6,722",
    ending_pay: "11,278",
    role: "Fullstack",
    stack: ["Rest API", "Docker", "Oracle", "Container"],
    img: DXC,
  },
  {
    company: "TikTok",
    job_title: "Tech Lead (SRE), Cloud Infrastructure",
    age: "4 days",
    location: "Singapore",
    rating: "3.6",
    starting_pay: "9,199",
    ending_pay: "15,122",
    role: "Reliability",
    stack: ["Linux"],
    img: TikTok,
  },
  {
    company: "Singtel",
    job_title: "Tech Lead",
    age: "1 day",
    location: "Singapore",
    rating: "3.8",
    starting_pay: "9,377",
    ending_pay: "14,918",
    role: "Fullstack",
    stack: ["API", "Strategy", "Modular"],
    img: Singtel,
  },
  {
    company: "Jala Tech",
    job_title: "Fullstack Engineer",
    age: "3 days",
    location: "Singapore",
    rating: "4.1",
    starting_pay: "8,312",
    ending_pay: "12,259",
    role: "Data Analyst",
    stack: ["Rest API", "API", "play"],
    img: Jala,
  },
  {
    company: "Coupang",
    job_title: "Staff, Back-end Engineer (Coupang Play)",
    age: "37 minutes",
    location: "Singapore",
    rating: "3.9",
    starting_pay: "12,500",
    ending_pay: "20,250",
    role: "Backend",
    stack: ["Rest API", "API", "play", "Modular", "Node.js", "JavaScript"],
    img: Coupang,
  },
  {
    company: "GovTech",
    job_title: "Technical Product Manager (Cloud)",
    age: "less than a minute",
    location: "Singapore",
    rating: "2.9",
    starting_pay: "6,722",
    ending_pay: "11,278",
    role: "PM",
    stack: ["Rest API", "Docker", "Oracle", "Container"],
    img: GovTech,
  },
  {
    company: "DXC Technology",
    job_title: "Tech Lead",
    age: "2 days",
    location: "Singapore",
    rating: "3.2",
    starting_pay: "6,722",
    ending_pay: "11,278",
    role: "Fullstack",
    stack: ["Rest API", "Docker", "Oracle", "Container"],
    img: DXC,
  },
];
